
// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview LinkedIn post generation flow.
 *
 * This file defines a Genkit flow for generating insightful LinkedIn posts based on selected themes,
 * with optional insights on trending topics. The goal is to produce content that feels human-written and authentic.
 *
 * @param input - The input for the generateLinkedInPost flow.
 * @returns The generated LinkedIn post.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const LinkedInPostTheme = z.enum([
  'Milestone',
  'Advice',
  'Behind-the-Scenes',
  'Personal Growth',
]);

const GenerateLinkedInPostInputSchema = z.object({
  theme: LinkedInPostTheme.describe('The theme of the LinkedIn post.'),
  topic: z.string().describe('The specific topic for the LinkedIn post.'),
  includeTrendingInsight: z
    .boolean()
    .describe(
      'Whether to include insights on why the chosen topic is trending.'
    ),
  voiceTone: z.string().optional().describe('The desired voice and tone for the generated content (e.g., Friendly & Casual, Professional & Clean, or a custom description).'),
});
export type GenerateLinkedInPostInput =
  z.infer<typeof GenerateLinkedInPostInputSchema>;

const GenerateLinkedInPostOutputSchema = z.object({
  post: z.string().describe('The generated LinkedIn post content. It should sound authentic, insightful, and human-written, as if one person is talking directly to another.'),
  trendingInsight: z
    .string()
    .optional()
    .describe('Insights on why the chosen topic is trending, if requested. This should also sound natural and insightful.'),
});
export type GenerateLinkedInPostOutput =
  z.infer<typeof GenerateLinkedInPostOutputSchema>;

export async function generateLinkedInPost(
  input: GenerateLinkedInPostInput
): Promise<GenerateLinkedInPostOutput> {
  return generateLinkedInPostFlow(input);
}

const generateLinkedInPostPrompt = ai.definePrompt({
  name: 'generateLinkedInPostPrompt',
  input: {schema: GenerateLinkedInPostInputSchema},
  output: {schema: GenerateLinkedInPostOutputSchema},
  prompt: `You are an expert LinkedIn content strategist and ghostwriter, highly skilled at crafting posts that sound *exactly* like a real person sharing their thoughts, experiences, and insights with their network. Your primary goal is to generate content that feels like a direct, human-to-human conversation. It must be authentic, insightful, and avoid any hint of being AI-generated.

  {{#if voiceTone}}
  Adopt the following voice and tone for your response: "{{voiceTone}}".
  Embody this tone deeply. This means carefully selecting vocabulary, sentence structure, emotional nuances, and overall style to perfectly match. The output must feel like it's coming from a genuine individual with this personality, speaking directly to their connections. If the user's specified tone allows, subtly infuse a contemporary, relatable feel, but prioritize the authenticity of the specified tone above all else. Avoid any robotic phrasing or overly polished text.
  {{else}}
  Use an engaging, insightful, and clear tone that is professional yet modern and approachable. Write as if you're talking to a respected colleague or connection. Use natural language, including contractions (e.g., "I'm", "it's", "you're"). The writing should flow conversationally, like a thoughtful professional sharing their genuine perspective. Use a strong, active voice where appropriate.
  {{/if}}

  Generate a LinkedIn post based on the following theme and topic.

  Theme: {{{theme}}}
  Topic: {{{topic}}}

  Crucial instructions for achieving a truly human, conversational feel:
  - **Direct Address**: Write as if you are speaking directly to your LinkedIn connections. Use "I" when sharing personal reflections or experiences, and consider using "you" when offering advice or posing questions to the reader.
  - **Storytelling (if applicable)**: For themes like 'Milestone' or 'Personal Growth', weave in a brief, relatable story or anecdote. Make it sound like a personal experience being shared.
  - **Authentic Language**: Use natural sentence structures. Avoid overly complex sentences or excessive jargon unless it's crucial for the topic and explained clearly and simply.
  - **Genuine Value**: The post must offer real advice, thoughtful reflections, or valuable observations. It should not feel like a summary of generic points.
  - **Conversational Flow**: Read it aloud. Does it sound like something a real person would say in a slightly professional but still personal context?
  - **Call to Engagement (Optional but Recommended)**: If appropriate for the topic and tone, end with an open-ended question or a prompt for discussion (e.g., "What are your thoughts on this?", "Has anyone else experienced something similar?"). This makes it feel more like a real conversation starter.
  - **Avoid AI Hallmarks**: Absolutely do NOT use:
    - Repetitive sentence starters (e.g., "In addition...", "Furthermore...", "It is important to note...").
    - Generic platitudes or overly common phrases that lack specific insight.
    - Overly polished, perfectly structured text that lacks personality or a natural cadence.
    - Numbered or bulleted lists unless the user's specific topic *explicitly* calls for a very direct list format and it can still be framed conversationally. Prefer paragraph form.
  - **Sound Human, Not Perfect**: The goal isn't just to be grammatically correct, but to sound like a real, thinking person wrote it.

  {{#if includeTrendingInsight}}
  Also, provide insights on why this topic might be currently trending on LinkedIn. Frame this insight in an engaging, modern, and human-sounding way. It should offer a thoughtful perspective, not just a list of facts. This too should sound conversational.
  {{/if}}

  The final post should be something a real individual would be genuinely proud to share on their LinkedIn profile, feeling it truly represents their voice and thoughts.
  The output for 'post' should be ONLY the post content itself.
  `,
});

const generateLinkedInPostFlow = ai.defineFlow(
  {
    name: 'generateLinkedInPostFlow',
    inputSchema: GenerateLinkedInPostInputSchema,
    outputSchema: GenerateLinkedInPostOutputSchema,
  },
  async (input): Promise<GenerateLinkedInPostOutput> => {
    try {
      const {output} = await generateLinkedInPostPrompt(input);
      return output!;
    } catch (e: any) {
      if (e instanceof Error && (e.message.includes('[503 Service Unavailable]') || e.message.includes('The model is overloaded'))) {
        throw new Error("The AI service is currently experiencing high demand and is temporarily unavailable. Please try again in a few moments.");
      }
      throw e;
    }
  }
);

