// Firebase integration has been removed.
// This file can be deleted or repurposed if other general lib utilities are needed.

// If you re-introduce Firebase, ensure your .env file is populated with:
// NEXT_PUBLIC_FIREBASE_API_KEY=...
// NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=...
// NEXT_PUBLIC_FIREBASE_PROJECT_ID=...
// NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=...
// NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=...
// NEXT_PUBLIC_FIREBASE_APP_ID=...
// NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=... // Optional
